plugins{
    id 'java'
    id 'war'
    id 'org.gretty' version '5.0.1'
}

gretty{
    contextPath='/'
    // servletContainer = 'tomcat10'
}


repositories{
    mavenCentral()
}
dependencies{

    providedRuntime 'jakarta.servlet:jakarta.servlet-api:6.0.0'
    providedRuntime 'jakarta.servlet.jsp:jakarta.servlet.jsp-api:3.1.1'
    //implementation 'jakarta.el:jakarta.el-api:6.0.1'
    //implementation 'jakarta.servlet.jsp.jstl:jakarta.servlet.jsp.jstl-api:3.0.2'
    implementation 'org.glassfish.web:jakarta.servlet.jsp.jstl:3.0.1'
    implementation 'org.springframework:spring-webmvc:6.2.11'
    implementation 'org.thymeleaf:thymeleaf:3.1.2.RELEASE'
    implementation 'org.thymeleaf:thymeleaf-spring6:3.1.2.RELEASE'
    implementation 'nz.net.ultraq.thymeleaf:thymeleaf-layout-dialect:3.2.0'
    implementation 'org.springframework:spring-jdbc:6.1.21'
    implementation 'com.mysql:mysql-connector-j:9.2.0'
    
    testImplementation "junit:junit:4.13.2"
}