plugins{
    id 'java'
    id 'war'
    id 'org.gretty' version '5.0.1'
}

gretty{
    contextPath='/'
}


repositories{
    mavenCentral()
}
dependencies{

    providedRuntime 'jakarta.servlet:jakarta.servlet-api:6.0.0'
    providedRuntime 'jakarta.servlet.jsp:jakarta.servlet.jsp-api:3.1.1'
    implementation 'jakarta.el:jakarta.el-api:6.0.1'
    implementation 'jakarta.servlet.jsp.jstl:jakarta.servlet.jsp.jstl-api:3.0.2'
    implementation 'org.glassfish.web:jakarta.servlet.jsp.jstl:3.0.1'
    implementation 'org.springframework:spring-webmvc:7.0.0'
    implementation 'com.mysql:mysql-connector-j:9.2.0'
    
    testImplementation "junit:junit:4.13.2"
}